name: ci-golang-workflow
on:
  pull_request:
    branches: 
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - run: go test
        working-directory: ${{env.working-directory}}
      - run: go run math.go
        working-directory: ${{env.working-directory}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: marcelonepomuceno/ci-with-go:latest