name: ci-golang-workflow
on:
  pull_request:
    branches: 
      - develop
strategy:
  matrix:
    go: ['1.14', '1.15']
jobs:
  check-application:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test
        working-directory: ${{env.working-directory}}
      - run: go run math.go
        working-directory: ${{env.working-directory}}